### PR TITLE
Adds table definitions for dYdX smart contracts

### PR DESCRIPTION
**Pull request by agbilotia1998**
Table Definition for smart contract: 
`PayableProxyForSoloMargin` - No Events
`Smart Contract #1`: 0x1e0447b19bb6ecfdae1e4ae1694b0c3659614e4e (Added)

### CODE REVIEW

**Comment by agbilotia1998** [comment]
@askeluv ping for review, in case auto review request is not generated.

**Comment by askeluv** [comment]
Hmm, this looks quite slim. In particular there are no trading events. I suspect `0x1e0447b19bb6ecfdae1e4ae1694b0c3659614e4e` is just a [proxy contract](https://etherscan.io/proxyContractChecker?a=0x1e0447b19bb6ecfdae1e4ae1694b0c3659614e4e), and so we would have to add the underlying implementation `0x56e7d4520abfecf10b38368b00723d9bd3c21ee1`.

The strange thing is that the trading events are not in the Etherscan ABI.
See https://github.com/dydxprotocol/solo/blob/10baf8e4c3fb9db4d0919043d3e6fdd6ba834046/contracts/protocol/lib/Events.sol
and
https://github.com/dydxprotocol/solo/blob/10baf8e4c3fb9db4d0919043d3e6fdd6ba834046/contracts/protocol/impl/OperationImpl.sol

I suspect we have to get the ABI some other way. Could you please check with the dYdX team if you find a way?

**Comment by askeluv** [comment]
Also for consistency, can you please name the dataset `dydx` (all lowercase)?

**Comment by agbilotia1998** [comment]
Hi @askeluv, I've changed the dataset name. Regarding ABIs I have tried to contact them and asked a way to get the same. I am waiting for their reply.
From the documentation, I got these contracts - https://docs.dydx.exchange/#/contracts

**Comment by agbilotia1998** [comment]
Hi @askeluv, I haven't received any response from the dYdX team yet, though it was forwarded to the concerned person.

**Comment by askeluv** [comment]
Hey @agbilotia1998 - thanks for the update. Where did you get in touch with them? Perhaps I can try following up.

**Comment by agbilotia1998** [comment]
Hi @askeluv, I dropped an email at contact@dydx.exchange you can get a follow up there.

**Comment by agbilotia1998** [comment]
Hi, @askeluv are any of the table definitions added in this PR useful? If not, can we close this PR?

**Comment by agbilotia1998** [comment]
@askeluv closing this PR for now. Let me know if there is any way to get table definitions for this.

**Comment by askeluv** [comment]
Hey @agbilotia1998 - sorry for the slow reply. In the end this turned out to be a pretty exceptional case unfortunately:
- It involved a proxy, which means you have to pick the underlying contract's ABI
- The underlying ABI was empty on Etherscan (haven't seen that before!) so had to compile it from the source code
- A datatype was used (`tuple`) which didn't work with our current JS library for parsing

... So for now we've put this on ice.

The good news is I've released the bounty regardless (currently pending) to compensate for your time - sorry it wasn't more straightforward, and I hope you'll consider contributing to future bounties!

**Comment by agbilotia1998** [comment]
Sure, no worries. I'll definitely look forward to other issues. Thanks!

**Pull request closed without merging**
