### PR TITLE
Add Aave

### PR DESCRIPTION
**Pull request by sebastiantf**
Added Aave

Used the Contract Parser: https://contract-parser.d5.ai

Found two proxy addresses:
1. 0x398eC7346DcD622eDc5ae82352F02bE94C62d119 --> 0x6d252baea75459ed0077410613c5f6e51cab4750

2. 0x3dfd23A6c5E8BbcFc9581d2E864a68feb6a076d3 --> 0x5766067108e534419ce13f05899bc3e3f4344948

Also found 16 smart contracts with the same contract name **`AToken`** and the same events. Named them with suffixes `_v2.json` to `_v16.json`

### CODE REVIEW

**Comment by sebastiantf** [comment]
@askeluv Please review

**Comment by askeluv** [comment]
Nice work @sebastiantf ! Just to double-check: you handled the proxy addresses as described [here](https://medium.com/@ASvanevik/how-to-add-proxy-ethereum-addresses-to-bigquery-d842ed001449), correct?

Also I wonder if we should leave the ATokens out and instead see if there's some kind of factory event we could use to automatically detect them (similar to how we handle Uniswap pools, etc).

Will let @medvedev1088 do the final review before deployment.

**Comment by sebastiantf** [comment]
Yes @askeluv. I found that post from your original post on adding smart contracts to BigQuery and followed it.

**Comment by medvedev1088** [comment]
> Also I wonder if we should leave the ATokens out and instead see if there's some kind of factory event we could use to automatically detect them (similar to how we handle Uniswap pools, etc).

I agree we should look deeper into it and find some factory method. Or combine multiple tables if they have the same interface. Having 13 version of the table will be difficult to maintain.

**Comment by askeluv** [comment]
I've asked for a factory in the Aave Discord: https://discordapp.com/channels/602826299974877205/636902500041228309/712685702285885502

One pragmatic alternative would be to keep 1 table, but list multiple contract addresses, similar to this: https://github.com/blockchain-etl/ethereum-etl-airflow/blob/0ef4cb068221271b821421fbc530b9a8101088dd/dags/resources/stages/parse/table_definitions/aragon/DAOFactory_event_DeployDAO.json#L15

**Comment by askeluv** [comment]
@sebastiantf would you mind doing the following:
1. Delete the "duplicates" of aToken contracts, and just keep 1 version for each event.
2. Replace the `contract_address` field similarly to what we've done here, where the list of addresses should be every aToken (16 in total?): https://github.com/blockchain-etl/ethereum-etl-airflow/blob/0ef4cb068221271b821421fbc530b9a8101088dd/dags/resources/stages/parse/table_definitions/aragon/DAOFactory_event_DeployDAO.json#L15

I will add another $20 as tip for your trouble! Hope you don't mind.

**Comment by sebastiantf** [comment]
I can do that @askeluv. I shall look into it now.

**Comment by sebastiantf** [comment]
@askeluv Just to make sure, there are 9 events that have 16 duplicates. I have to modify the `contract_address` field of the first version of each of those 9 events' json.
Is that correct?

**Comment by sebastiantf** [comment]
@askeluv I have made the changes. Please review.

**Comment by askeluv** [comment]
Great stuff, LGTM. Will let @medvedev1088 make the final review.

**Comment by askeluv** [comment]
Paid out the bounty plus $20 tip as promised @sebastiantf - great work! Thanks

**Comment by sebastiantf** [comment]
Thanks @askeluv! Looking forward for more opportunities to work with you.

**Pull request merged**
