### PR TITLE
Initial RAI events

### PR DESCRIPTION
**Pull request by bkellerman**
Initial events for RAI [](https://reflexer.finance/)

I used the Contract Parser: https://contract-parser.d5.ai to generate.

@medvedev1088

### CODE REVIEW

**Comment by araa47** [comment]
Hey @bkellerman  I noticed that you have included Uniswap Pool events here too. 

This folder should only contain events specific to RAI, since the Uniswap events are already registered and can be extracted using the following sql.

Example: Mint
```
SELECT 
    * 
FROM 
    `blockchain-etl-internal.ethereum_uniswap.UniswapV2Pair_event_Mint` 
WHERE 
    contract_address = '0x8ae720a71622e824f576b4a8c03031066548a3b1' -- RAI/WETH UNI-v2
```


Can you help with cleaning up the PR, so only RAI contracts are under the following directory `dags/resources/stages/parse/table_definitions/rai/`

**Comment by bkellerman** [comment]
Just removed them. Thanks @araa47

**Review by araa47 — COMMENTED** [review]
lgtm

**Comment by araa47** [comment]
@bkellerman , this should be live now

**Pull request merged**
