### PR TITLE
Add stETH and ENS aToken addresses

### PR DESCRIPTION
**Pull request by marcinja**
@medvedev1088

### CODE REVIEW

**Comment by araa47** [comment]
Hey @marcinja can you make sure the new addresses added are all lower case, thank you

**Comment by marcinja** [comment]
@araa47 pushed a fix for that. Thanks

**Comment by WatFu** [comment]
@araa47 Do you mind reviewing this again?

**Comment by araa47** [comment]
Hey @WatFu , @marcinja sorry for the delay. Merged. The tables should be in BQ now.

**Comment by WatFu** [comment]
Thanks!

**Pull request merged**
