### PR TITLE
added arbitrum uniswap v3 factory and pools events, removed arbitrum uniswap factory nft events

### PR DESCRIPTION
**Pull request by liordavid**
## What?
added arbitrum uniswap v3 factory and pools events, removed arbitrum uniswap factory nft events

## How? 
ie: I used [abi-parser](https://nansen-contract-parser-prod.web.app/) or cli tools to build the table definitions

### CODE REVIEW

**Comment by medvedev1088** [comment]
What does "_open" suffix in the dataset name mean? Would it make sense to have "arbitrum_uniswap_v3" dataset instead of having separate "arbitrum_uniswap_v3_nft_positions" and "arbitrum_uniswap_v3_open"?

**Comment by liordavid** [comment]
I deleted arbitrum_uniswap_v3_nft_positions as it is not needed.
In general, the purpose is to have log events of mint, burn and swap.
I will remove the "_open" and change it to "arbitrum_uniswap_v3".

**Comment by liordavid** [comment]
Hi [medvedev1088](https://github.com/medvedev1088), I fixed this dataset name as we discussed. will be glad for your review.

**Comment by liordavid** [comment]
hi @medvedev1088 , i expected this commit to creating a dataset on big query with arbitrum date coming from log events of the contract I put in the JSON files. in practice, the same contract address also exists in Ethereum main net and the data I see in the tables is the Ethereum main net events, how and where do I specify the network to work with? Is it some definition on the JSON files or in the blockchain-air-flow project? I see some of the datasets work with layer 2 networks? can you please refer me to an article or guidance on that?

**Pull request merged**
