### PR TITLE
Added basic Dai exchange events for Uniswap DAI/ETH exchange

### PR DESCRIPTION
**Pull request by ianlapham**
- Add 4 tables in a new  Uniswap directory 
- tracks events on the DAI/ETH exchange

### CODE REVIEW

**Comment by askeluv** [comment]
Great to have more contributors onboard for event parsing @ianlapham ! PR looks good to me, but subject to @medvedev1088 's review.

Since Uniswap can issue new pools (and thus new contracts) we have discussed building a "layer 2" for these kinds of contract-generated contracts. But for now I think we should just ship this, and we can think more about this later.

**Comment by medvedev1088** [comment]
Agree. I'm going to deploy it to the blockchain-etl.uniswap dataset in BigQuery.

**Comment by medvedev1088** [comment]
Here is a tool that @askeluv has implemented to simplify table definition creation: https://abi-parser.nvk.now.sh.

**Comment by ianlapham** [comment]
Hey guys, somehow just seeing your response here. Thanks a bunch for getting this stuff up its really helpful for our analytics.

**Comment by askeluv** [comment]
Great to hear @ianlapham ! Have you seen the latest datasets that include all Uniswap pools? We just added those this week. Here's the PR: #55

**Pull request merged**
