### PR TITLE
Feature: YFI 

### PR DESCRIPTION
**Pull request by sambacha**
## Feature: initial YFI addition

- [x] Used the Contract Parser: https://contract-parser.d5.ai
- [x] Ensured Event Transfer and Approval for first Strategy Vault to be included 
- [x] Request Maintainer @medvedev1088 

### Questions 

As YFI has the concept of Strategies, would it be best to separate these into sub-folders in the directory? That is what I have done but wanted to make sure before I added the rest, so this is just the minimal viable feature-set for inclusion (I think). 

### Releases 

-- Release this work under any CLA provision if so required

Thank you,

Sam

### CODE REVIEW

**Comment by medvedev1088** [comment]
Thanks for the PR. 

Could you replace <INSERT_DATASET_NAME> with yfi and <TABLE_PREFIX> with the respective contract name. Also all file names must be equal to the `table_name` field inside json. 

Please also make all files be directly inside the `yfi` folder and BigQuery doesn't allow subfolders in a dataset.

Thanks.

**Comment by sambacha** [comment]
> Thanks for the PR and sorry for the late reply.
> 
> Could you replace <INSERT_DATASET_NAME> with yfi and <TABLE_PREFIX> with the respective contract name. Also all file names must be equal to the `table_name` field inside json.
> 
> Please also make all files be directly inside the `yfi` folder and BigQuery doesn't allow subfolders in a dataset.
> 
> Thanks.

Will update this per requested changes, also would it be helpful to separate YFI into two folders, one for Version1 and the other for Version2? 

Thanks,

Sam

**Comment by medvedev1088** [comment]
> would it be helpful to separate YFI into two folders, one for Version1 and the other for Version2?

The approach we've taken with regards to versioning is we use the same dataset e.g. yfi, but append a version to contract name in the table name, e.g. `<ContractName>_v2_call_getName`

**Review by medvedev1088 — CHANGES_REQUESTED** [review]
File names should follow the convention, all files should be inside the yfi folder

**Pull request closed without merging**
