### PR TITLE
angle additional calls

### PR DESCRIPTION
**Pull request by AyadiGithub**
## What?
Add additional angle calls and change the contract source for perpetual events/calls

## How? 
I used [abi-parser](https://nansen-contract-parser-prod.web.app/) to build the table definitions

### CODE REVIEW

**Comment by AyadiGithub** [comment]
@TimNooren kindly check this PR? appreciated. Thank you and happy holidays!

**Comment by SimonCousaert** [comment]
@TimNooren friendly reminder :)

**Comment by TimNooren** [comment]
Renaming `StableMasterFront_event_withdraw` → `StableMasterFront_call_withdraw` means a new table will be created. @araa47 or @medvedev1088, can I ask you to delete `blockchain-etl.ethereum_angle.StableMasterFront_event_withdraw` at some point once this is merged?

I will also add a check to make sure the table name matches the correct format for its type to avoid this in the future.

**Review by TimNooren — APPROVED** [review]

**Comment by TimNooren** [comment]
@AyadiGithub @SimonCousaert, sorry for the delay, I was off until today. Data should be available, please let me know if you find any issues:)

**Pull request merged**
