### PR TITLE
Implement refs support in contract_address for parsing logs

### PR DESCRIPTION
**Pull request by medvedev1088**
https://github.com/blockchain-etl/ethereum-etl-airflow/issues/51

### CODE REVIEW

**Comment by askeluv** [comment]
Nice! One thing I believe we're missing is the contract address of the "child contract" in the resulting event table. Which means we don't know which child contract produced the event.

I should have included this in the spec - sorry.

What if we simply add `contract_address` to all event tables?

**Comment by medvedev1088** [comment]
> What if we simply add contract_address to all event tables?

Yes I think it's the simplest solution. I'll need to do full re-parse existing tables though.

**Comment by medvedev1088** [comment]
Realised that it would be even simple if we had:

```
"contract_address_ref": {
  "table": "Mintbase_event_StoreLaunch",
  "field": "store"
}
```

This way we're also agnostic of the technology, i.e. we could use the same table definition to parse in Python in real time.

I'm gonna merge it for now anyway and later we can refactor if necessary.

**Comment by medvedev1088** [comment]
Deployed to `blockchain-etl.ethereum_mintbase`

**Pull request merged**
