### PR TITLE
Added Sandbox land events Smart Contract Parser

### PR DESCRIPTION
**Pull request by Dwaynekj**
Used the Contract Parser: https://contract-parser.d5.ai

### CODE REVIEW

**Comment by araa47** [comment]
Hey @Dwaynekj the PR looks good but I think it might be neater if  we change the dataset name to `sandbox` instead of `sandbox_land` ? Plus also update the dataset name in the json files to `sandbox`

https://github.com/blockchain-etl/ethereum-etl-airflow/blob/3d1400b15ba4f2d43ec1fe6ddc9ce66457eddbec/dags/resources/stages/parse/table_definitions/sandbox_land/Land_event_AdminChanged.json#L25

**Comment by Dwaynekj** [comment]
@araa47 thanks for the comment!

With regards to naming, it doesn't matter that I'm looking to capture the Sandbox Land events not the Sand contract events?


Also I noticed that I may have gotten the old Sandbox Contract. The new one appears to be `https://etherscan.io/address/0x5cc5b05a8a13e3fbdb0bb9fccd98d38e50f90c38` whereas I used `https://etherscan.io/address/0x50f5474724e0ee42d9a4e711ccfb275809fd6d4a`

I will update my pr to reflect that

**Comment by araa47** [comment]
Hey @Dwaynekj the new contract uve added is actually a Proxy. 

The proxy contracts will only build 2 tables with the following events:

- AdminChanged
- Upgraded 

You might actually be interested in the implementation contract over here rather than a proxy contract. 

Id suggest to rename the dataset to `sandbox` and also input all the multiple implementation contracts like this https://github.com/blockchain-etl/ethereum-etl-airflow/blob/425ebdbb573fb4db2842ede571ef79f3f4d07298/dags/resources/stages/parse/table_definitions/synthetix/sBTC_event_SelfDestructTerminated.json#L9 if they follow the same spec.

If they dont and event signatures vary I would suggest to parse them individually (different json files for each contract) 


Latest implementation contract can be seen when visiting this link on Etherscan: https://etherscan.io/address/0x5CC5B05a8A13E3fBDB0BB9FcCd98D38e50F90c38#readProxyContract . It points to https://etherscan.io/address/0x1fc6479bdc7511c6803aff2f477e0fd3171606e0#code as the latest implementation

**Comment by Dwaynekj** [comment]
@araa47 Thanks for the tips!

I've reimported the jsons for the implementation contract (new and old) making note to adjust `contract_address` to account for
https://etherscan.io/address/0x50f5474724e0ee42d9a4e711ccfb275809fd6d4a and
https://etherscan.io/address/0x1fc6479bdc7511c6803aff2f477e0fd3171606e0

**Pull request merged**
