### PR TITLE
create dataset, add events for the factory

### PR DESCRIPTION
**Pull request by markusbkoch**
It seems 1 inch recently [rebranded Mooniswap and deployed a new factory](https://github.com/1inch-exchange/1inch-liquidity-protocol/commit/ca3e0483a81cdee57208558dffbc76dd4c7047d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

### CODE REVIEW

**Comment by markusbkoch** [comment]
@medvedev1088 can you review please? Thanks

**Comment by medvedev1088** [comment]
> @medvedev1088 can you review please? Thanks

we have the `mooniswap` dataset. Should these contracts go there with the `_v2` suffix?

**Comment by markusbkoch** [comment]
Sorry, I should have pointed to [this commit instead](https://github.com/1inch-exchange/1inch-liquidity-protocol/commit/af4f41b28dde5e3a96613c19eb55b7d2cc0e572b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1) when referring to the rebranding. The Mooniswap term seems to have been deprecated, even though it still shows up in contracts and arguments names.

**Comment by medvedev1088** [comment]
Oh I see, makes sense now.

**Comment by medvedev1088** [comment]
@markusbkoch it's deployed now

**Pull request merged**
